package modules

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"time"

	"github.com/chmenegatti/devdash/internal/state"
)

// GenerateReportFile creates a markdown report for the current dashboard state
// and writes it to the project directory.
func GenerateReportFile(projectDir string, ds state.Dashboard) (string, error) {
	now := time.Now()
	filename := fmt.Sprintf("devdash-report-%s.md", now.Format("20060102-150405"))
	path := filepath.Join(projectDir, filename)

	content := generateMarkdownReport(ds, now)
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return "", err
	}
	return path, nil
}

func generateMarkdownReport(ds state.Dashboard, generatedAt time.Time) string {
	var sb strings.Builder

	fmt.Fprintf(&sb, "# 🧾 devdash Report\n\n")
	fmt.Fprintf(&sb, "> **Project:** `%s`  \n", ds.ProjectName)
	fmt.Fprintf(&sb, "> **Path:** `%s`  \n", ds.ProjectDir)
	fmt.Fprintf(&sb, "> **Generated at:** %s\n\n", generatedAt.Format("2006-01-02 15:04:05 MST"))

	sb.WriteString("## 📌 Executive Summary\n\n")
	sb.WriteString("| Module | Status | Highlights |\n")
	sb.WriteString("|---|---|---|\n")
	fmt.Fprintf(&sb, "| 🧪 Tests | %s | %s |\n", statusBadge(ds.Tests.Status), testsSummary(ds.Tests))
	fmt.Fprintf(&sb, "| 📊 Coverage | %s | %.1f%% |\n", statusBadge(ds.Coverage.Status), ds.Coverage.Percentage)
	fmt.Fprintf(&sb, "| 🔍 Lint | %s | %d issue(s) |\n", statusBadge(ds.Lint.Status), len(ds.Lint.Issues))
	fmt.Fprintf(&sb, "| ⚡ Benchmarks | %s | %d benchmark(s) |\n", statusBadge(ds.Benchmarks.Status), len(ds.Benchmarks.Entries))
	fmt.Fprintf(&sb, "| 📦 Binary | %s | %s |\n", statusBadge(ds.Binary.Status), formatBytes(ds.Binary.Size))
	fmt.Fprintf(&sb, "| 🌿 Git | %s | %d change(s) |\n", statusBadge(ds.Git.Status), gitTotal(ds.Git))
	fmt.Fprintf(&sb, "| 📚 Dependencies | %s | %d module(s) |\n\n", statusBadge(ds.Deps.Status), len(ds.Deps.Deps))

	writeTestsSection(&sb, ds.Tests)
	writeCoverageSection(&sb, ds.Coverage)
	writeLintSection(&sb, ds.Lint)
	writeBenchSection(&sb, ds.Benchmarks)
	writeBinarySection(&sb, ds.Binary)
	writeGitSection(&sb, ds.Git)
	writeDepsSection(&sb, ds.Deps)

	sb.WriteString("---\n\n")
	sb.WriteString("_Generated by **devdash**_ ✨\n")

	return sb.String()
}

func writeTestsSection(sb *strings.Builder, r state.TestsResult) {
	testCases, failedCount := resolveTestCounts(r)

	sb.WriteString("## 🧪 Tests\n\n")
	fmt.Fprintf(sb, "- **Status:** %s\n", statusBadge(r.Status))
	fmt.Fprintf(sb, "- **Passed:** %t\n", r.Passed)
	fmt.Fprintf(sb, "- **Test cases:** %d\n", testCases)
	fmt.Fprintf(sb, "- **Failed tests:** %d\n", failedCount)
	fmt.Fprintf(sb, "- **Packages:** %d\n", r.Packages)
	fmt.Fprintf(sb, "- **Duration:** %s\n\n", r.Duration)
	sb.WriteString("- **Validation scope:** all project packages (`go test -v -count=1 ./...`)\n\n")
	if r.Err != "" {
		fmt.Fprintf(sb, "> ⚠️ %s\n\n", r.Err)
	}

	passedTests, failedTests := extractTestCaseResults(r.Output)
	if len(passedTests) > 0 || len(failedTests) > 0 {
		sb.WriteString("### Test Cases\n\n")
		for _, testName := range passedTests {
			fmt.Fprintf(sb, "- ✅ %s\n", testName)
		}
		for _, testName := range failedTests {
			fmt.Fprintf(sb, "- ❌ %s\n", testName)
		}
		sb.WriteString("\n")
	}

	if strings.TrimSpace(r.Output) != "" {
		sb.WriteString("### Raw Output\n\n```text\n")
		sb.WriteString(strings.TrimSpace(r.Output))
		sb.WriteString("\n```\n\n")
	}
}

func writeCoverageSection(sb *strings.Builder, r state.CoverageResult) {
	sb.WriteString("## 📊 Coverage\n\n")
	fmt.Fprintf(sb, "- **Status:** %s\n", statusBadge(r.Status))
	fmt.Fprintf(sb, "- **Coverage:** %.1f%%\n\n", r.Percentage)
	if r.Err != "" {
		fmt.Fprintf(sb, "> ⚠️ %s\n\n", r.Err)
	}
	if strings.TrimSpace(r.Output) != "" {
		sb.WriteString("### Raw Output\n\n```text\n")
		sb.WriteString(strings.TrimSpace(r.Output))
		sb.WriteString("\n```\n\n")
	}
}

func writeLintSection(sb *strings.Builder, r state.LintResult) {
	sb.WriteString("## 🔍 Lint\n\n")
	fmt.Fprintf(sb, "- **Status:** %s\n", statusBadge(r.Status))
	fmt.Fprintf(sb, "- **Issues:** %d\n\n", len(r.Issues))
	if r.Err != "" {
		fmt.Fprintf(sb, "> ⚠️ %s\n\n", r.Err)
	}
	if len(r.Issues) > 0 {
		sb.WriteString("### Issues\n\n")
		for i, issue := range r.Issues {
			fmt.Fprintf(sb, "%d. %s\n", i+1, issue)
		}
		sb.WriteString("\n")
	}
}

func writeBenchSection(sb *strings.Builder, r state.BenchmarkResult) {
	sb.WriteString("## ⚡ Benchmarks\n\n")
	fmt.Fprintf(sb, "- **Status:** %s\n", statusBadge(r.Status))
	fmt.Fprintf(sb, "- **Entries:** %d\n\n", len(r.Entries))
	if r.Err != "" {
		fmt.Fprintf(sb, "> ⚠️ %s\n\n", r.Err)
	}
	if len(r.Entries) > 0 {
		sb.WriteString("| Benchmark | Iterations | ns/op |\n")
		sb.WriteString("|---|---:|---:|\n")
		for _, e := range r.Entries {
			fmt.Fprintf(sb, "| %s | %d | %.1f |\n", e.Name, e.Iterations, e.NsPerOp)
		}
		sb.WriteString("\n")
	}
	if strings.TrimSpace(r.Output) != "" {
		sb.WriteString("### Raw Output\n\n```text\n")
		sb.WriteString(strings.TrimSpace(r.Output))
		sb.WriteString("\n```\n\n")
	}
}

func writeBinarySection(sb *strings.Builder, r state.BinaryResult) {
	sb.WriteString("## 📦 Binary\n\n")
	fmt.Fprintf(sb, "- **Status:** %s\n", statusBadge(r.Status))
	fmt.Fprintf(sb, "- **Size:** %s\n\n", formatBytes(r.Size))
	if r.Err != "" {
		fmt.Fprintf(sb, "> ⚠️ %s\n\n", r.Err)
	}
}

func writeGitSection(sb *strings.Builder, r state.GitResult) {
	sb.WriteString("## 🌿 Git Status\n\n")
	fmt.Fprintf(sb, "- **Status:** %s\n", statusBadge(r.Status))
	fmt.Fprintf(sb, "- **Changed files:** %d\n\n", gitTotal(r))
	if r.Err != "" {
		fmt.Fprintf(sb, "> ⚠️ %s\n\n", r.Err)
	}
	writeGitList(sb, "Modified", r.Modified)
	writeGitList(sb, "Added", r.Added)
	writeGitList(sb, "Deleted", r.Deleted)
	writeGitList(sb, "Other/Untracked", r.Other)
}

func writeGitList(sb *strings.Builder, title string, items []string) {
	if len(items) == 0 {
		return
	}
	fmt.Fprintf(sb, "### %s\n\n", title)
	for _, item := range items {
		fmt.Fprintf(sb, "- `%s`\n", item)
	}
	sb.WriteString("\n")
}

func writeDepsSection(sb *strings.Builder, r state.DepsResult) {
	sb.WriteString("## 📚 Dependencies\n\n")
	fmt.Fprintf(sb, "- **Status:** %s\n", statusBadge(r.Status))
	fmt.Fprintf(sb, "- **Total modules:** %d\n\n", len(r.Deps))
	if r.Err != "" {
		fmt.Fprintf(sb, "> ⚠️ %s\n\n", r.Err)
	}
	if len(r.Deps) > 0 {
		sb.WriteString("### Module List\n\n")
		for _, dep := range r.Deps {
			fmt.Fprintf(sb, "- `%s`\n", dep)
		}
		sb.WriteString("\n")
	}
}

func statusBadge(s state.Status) string {
	switch s {
	case state.StatusDone:
		return "✅ Done"
	case state.StatusRunning:
		return "🏃 Running"
	case state.StatusError:
		return "❌ Error"
	default:
		return "⏳ Idle"
	}
}

func testsSummary(r state.TestsResult) string {
	if r.Status == state.StatusDone {
		tests, failedTests := resolveTestCounts(r)
		if r.Passed {
			return fmt.Sprintf("PASS (%d tests in %s)", tests, r.Duration)
		}
		return fmt.Sprintf("FAIL (%d tests, %d failed, in %s)", tests, failedTests, r.Duration)
	}
	if r.Err != "" {
		return r.Err
	}
	return "No run yet"
}

func resolveTestCounts(r state.TestsResult) (tests int, failed int) {
	passedTests, failedTests := extractTestCaseResults(r.Output)
	if len(passedTests)+len(failedTests) > 0 {
		return len(passedTests) + len(failedTests), len(failedTests)
	}

	tests = r.TestCases
	failed = r.FailedTests
	if tests == 0 {
		tests = r.Packages
	}
	return tests, failed
}

func extractTestCaseResults(output string) (passed []string, failed []string) {
	if strings.TrimSpace(output) == "" {
		return nil, nil
	}

	passRe := regexp.MustCompile(`^--- PASS: (\S+)`)
	failRe := regexp.MustCompile(`^--- FAIL: (\S+)`)

	for _, line := range strings.Split(output, "\n") {
		line = strings.TrimSpace(line)
		if m := passRe.FindStringSubmatch(line); m != nil {
			passed = append(passed, m[1])
			continue
		}
		if m := failRe.FindStringSubmatch(line); m != nil {
			failed = append(failed, m[1])
		}
	}

	return passed, failed
}

func gitTotal(r state.GitResult) int {
	return len(r.Modified) + len(r.Added) + len(r.Deleted) + len(r.Other)
}

func formatBytes(b int64) string {
	const (
		kb = 1024
		mb = kb * 1024
		gb = mb * 1024
	)
	switch {
	case b >= gb:
		return fmt.Sprintf("%.1f GB", float64(b)/float64(gb))
	case b >= mb:
		return fmt.Sprintf("%.1f MB", float64(b)/float64(mb))
	case b >= kb:
		return fmt.Sprintf("%.1f KB", float64(b)/float64(kb))
	default:
		return fmt.Sprintf("%d B", b)
	}
}
